In [1]:
import numpy as np

Q1


In [33]:
arr=np.arange(1,101)
even_num=arr[arr%2==0]
print(even_num)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


Q2


In [35]:
result=arr.copy()
result[arr % 2==0]=1
result[arr %2 !=0]=-1
print(result)

[-1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1
 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1
 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1
 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1
 -1  1 -1  1]


Q3


In [48]:
arr3 = np.random.randint(0, 10, size=(5,5))  
print(arr3)
min_value = np.min(arr3)
min_index =np.unravel_index(np.argmin(arr3), arr3.shape)
max_value = np.max(arr3)
max_index = np.unravel_index(np.argmax(arr3), arr3.shape)
print("Minimum value:", min_value, "at index:", min_index)
print("Maximum value:", max_value, "at index:", max_index)

[[3 2 4 0 1]
 [5 0 0 5 0]
 [2 2 9 9 3]
 [0 0 7 8 6]
 [2 5 0 6 1]]
Minimum value: 0 at index: (np.int64(0), np.int64(3))
Maximum value: 9 at index: (np.int64(2), np.int64(2))


Q4


In [52]:
arr4= np.arange(1,7).reshape((2,3))

rotated = arr4[::-1, ::-1]
print(rotated)


[[6 5 4]
 [3 2 1]]


Q5

In [53]:
I=np.zeros((3,3),dtype=int)
np.fill_diagonal(I,1)
print(I)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


Q6

In [57]:
arr=np.arange(1,11)
arr1=arr.reshape(2,5)
print(arr1)
print(arr1.T)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


Q7

In [62]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
position = np.where(a == b)
print("Positions where a equals b:", position[0])



Positions where a equals b: [2]


Q8

In [63]:
arr=np.ones((5,5),dtype=int)
arr[1:-1,1:-1]=0
print(arr)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


Q9

In [74]:
arr3,arr4= np.random.randint(0, 10, size=(5,5)) ,np.random.randint(0, 10, size=(5,5))
print("Array a:\n",arr3)
print("Array b:\n",arr4)    
arr3[arr3>arr4]=arr4[arr3>arr4]
print("Modified array a:\n",arr3)

Array a:
 [[1 1 7 7 6]
 [3 9 9 5 0]
 [9 9 1 1 4]
 [3 4 1 9 6]
 [1 4 6 3 9]]
Array b:
 [[0 8 3 9 6]
 [4 0 2 2 0]
 [1 3 6 0 0]
 [1 9 2 6 1]
 [8 5 1 8 0]]
Modified array a:
 [[0 1 3 7 6]
 [3 0 2 2 0]
 [1 3 1 0 0]
 [1 4 1 6 1]
 [1 4 1 3 0]]


Q10

In [80]:
arr=np.random.randint(0,10,size=(3,3))
normalized_arr=(arr-np.min(arr))/(np.max(arr)-np.min(arr))
print(arr)
print("Normalized array:\n",normalized_arr)

[[3 1 2]
 [5 8 3]
 [8 5 7]]
Normalized array:
 [[0.28571429 0.         0.14285714]
 [0.57142857 1.         0.28571429]
 [1.         0.57142857 0.85714286]]


Q11

In [88]:
arr=np.arange(1,26).reshape(5,5)
result=arr.copy()
result1=result[(result%3==0) & (result%5==0)]
print(result1)

[15]


Q12

In [89]:
a=np.arange(10,101,10)
a[a % 6 == 0] = a[a % 6 == 0] ** 2
print(a)


[  10   20  900   40   50 3600   70   80 8100  100]


Q13

In [91]:
arr=np.random.randint(1,17,size=(4,4))
arr[:,[0,3]]=arr[:,[3,0]]
print(arr)


[[ 7  8 15 13]
 [ 9 13 16 13]
 [ 8 11  7  9]
 [15  1 13 12]]


Q14

In [92]:
arr1=np.random.randint(1,10,size=10)
arr2=np.random.randint(1,10,size=10)
common_elements=np.intersect1d(arr1,arr2)
print("Array 1:",arr1)
print("Array 2:",arr2)
print("Common elements:",common_elements)

Array 1: [2 8 5 4 9 9 8 9 9 9]
Array 2: [3 7 1 4 8 9 2 5 1 5]
Common elements: [2 4 5 8 9]


Q15

In [4]:
a = np.random.randint(1, 11,size=10)
result = np.r_[a[1]-a[0], a[2:]-a[:-2], a[-1]-a[-2]]
print(result)


[ 3  6  0 -6 -4  5  4  0 -1 -3]


Q16

In [9]:
a = np.random.randint(1, 11,size=(6,6))
max_idx = a.argmax(axis=1)
result = a[np.arange(a.shape[0]), max_idx]=0
print("Array:\n", a)

Array:
 [[4 6 2 3 1 0]
 [7 1 0 3 1 1]
 [9 7 4 2 0 3]
 [1 6 1 4 2 0]
 [8 0 2 7 3 7]
 [5 2 0 8 3 3]]


Q17

In [ ]:
arr =np.array([1,2,3,2,3,3,1,2,4,3,5])
most_frequent = np.bincount(arr).argmax()
print("Most frequent element:", most_frequent)


Most frequent element: 3
[0 2 3 4 1 1]


Q18

In [23]:
arr=np.random.randint(1,26,size=(5,5))
arr1=arr.copy()
arr1.sort(axis=1)
print("Original array:\n",arr)
print("Row-wise sorted array:\n",arr1)

Original array:
 [[ 9  6 17  6 16]
 [23 11 12 21 19]
 [ 5 12 16 19  1]
 [12  4 14  7 21]
 [20 16 19 20  8]]
Row-wise sorted array:
 [[ 6  6  9 16 17]
 [11 12 19 21 23]
 [ 1  5 12 16 19]
 [ 4  7 12 14 21]
 [ 8 16 19 20 20]]


Q19

In [36]:
arr=np.random.randint(1,17,size=(4,4))
result = (arr > arr.mean()).astype(int)
print(result)


[[1 0 0 1]
 [1 0 1 1]
 [0 0 0 0]
 [0 1 0 0]]


Q20

In [37]:
a=np.arange(1,10).reshape(3,3)
b=np.arange(10,19).reshape(3,3)
c=np.zeros((3,3),dtype=int)
for i in range(3):
    for j in range(3):
        for k in range(3):
            c[i][j]+=a[i][k]*b[k][j]
print(c)




[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
